server:
  port: 9000

spring:
  application:
    name: auth-server
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: INFO

